# Generated by Django 5.2.5 on 2025-11-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0005_alter_medioacreditacion_tipo_medio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medioacreditacion',
            name='tipo_medio',
            field=models.CharField(choices=[('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Medio de Acreditación'),
        ),
    ]
