# Generated by Django 5.2.5 on 2025-11-14 21:46

from django.db import migrations, models

def create_default_limites(apps, schema_editor):
    LimiteClienteTipo = apps.get_model('clientes', 'LimiteClienteTipo')
    defaults = [
        {"tipo_cliente": "minorista", "limite_diario": 2000000, "limite_mensual": 10000000},
        {"tipo_cliente": "corporativo", "limite_diario": 5000000, "limite_mensual": 25000000},
        {"tipo_cliente": "vip", "limite_diario": 10000000, "limite_mensual": 50000000},
    ]
    for entry in defaults:
        LimiteClienteTipo.objects.get_or_create(tipo_cliente=entry["tipo_cliente"], defaults=entry)

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_limitepyg_limitemoneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteClienteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('minorista', 'Minorista'), ('corporativo', 'Corporativo'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('limite_diario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('limite_mensual', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.RunPython(create_default_limites),
    ]
