# Generated by Django 5.2.5 on 2025-10-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0003_alter_tasacambio_options_tasacambio_es_automatica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioBaseComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio base')),
                ('comision_compra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión de compra (%)')),
                ('comision_venta', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comisión de venta (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_comisiones', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Precio base y comisión',
                'verbose_name_plural': 'Precios base y comisiones',
                'unique_together': {('moneda',)},
            },
        ),
    ]
