# Generated by Django 5.2.5 on 2025-10-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0004_preciobasecomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciobasecomision',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comisión de compra'),
        ),
        migrations.AlterField(
            model_name='preciobasecomision',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Comisión de venta'),
        ),
    ]
