# Generated by Django 5.2.5 on 2025-10-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0005_alter_preciobasecomision_comision_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciobasecomision',
            name='compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='preciobasecomision',
            name='venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Venta'),
        ),
    ]
