# Generated by Django 5.2.5 on 2025-10-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0006_preciobasecomision_compra_preciobasecomision_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciobasecomision',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='preciobasecomision',
            name='venta',
        ),
    ]
