# Generated by Django 5.2.5 on 2025-10-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0007_remove_preciobasecomision_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='variacion',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, verbose_name='Variación %'),
        ),
    ]
