# Generated by Django 5.2.5 on 2025-10-23 14:07

from django.db import migrations, models


def crear_comisiones_iniciales(apps, schema_editor):
    ComisionMetodoPago = apps.get_model('payments', 'ComisionMetodoPago')
    for tipo, nombre in [
        ("tarjeta", "Tarjeta de crédito"),
        ("transferencia", "Transferencia"),
        ("billetera", "Billetera")
    ]:
        ComisionMetodoPago.objects.get_or_create(tipo_metodo=tipo, defaults={"porcentaje_comision": 0.00})

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_paymentmethod_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionMetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metodo', models.CharField(choices=[('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia'), ('billetera', 'Billetera')], max_length=20, unique=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión (ej: 5.00)', max_digits=5)),
            ],
            options={
                'verbose_name': 'Comisión por método de pago',
                'verbose_name_plural': 'Comisiones por método de pago',
            },
        ),
        migrations.RunPython(crear_comisiones_iniciales),
    ]
