# Generated by Django 5.2.5 on 2025-11-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_descuentometodopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_banco',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_beneficiario',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_cuenta',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_fecha_emision',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_moneda',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_monto',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_numero',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cheque_orden',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tarjeta_cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tarjeta_marca',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tarjeta_nombre',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tarjeta_numero',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tarjeta_vencimiento',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Método de Pago'),
        ),
    ]
