# Generated by Django 5.2.5 on 2025-11-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_remove_paymentmethod_cheque_banco_and_more'),
        ('payments', '0012_auto_poblar_comisiones_metodo_pago'),
    ]

    operations = [
    ]
