# Generated by Django 5.2.5 on 2025-11-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_poblar_comisiones_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionmetodopago',
            name='tipo_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia'), ('billetera', 'Billetera')], max_length=20, unique=True),
        ),
    ]
