# Generated by Django 5.2.5 on 2025-11-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_crear_metodos_pago_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera')], default='cuenta_bancaria', max_length=20, verbose_name='Tipo de Método de Pago'),
        ),
    ]
