# Generated by Django 5.2.5 on 2025-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionmetodopago',
            name='tipo_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera Digital')], max_length=20, unique=True),
        ),
    ]
