# Generated by Django 5.2.5 on 2025-11-24 15:00

from django.db import migrations


def update_transferencia_to_cuenta_bancaria(apps, schema_editor):
    """
    Actualiza todos los registros de 'transferencia' a 'cuenta_bancaria'
    """
    ComisionMetodoPago = apps.get_model('payments', 'ComisionMetodoPago')
    
    # Actualizar registros de ComisionMetodoPago
    ComisionMetodoPago.objects.filter(tipo_metodo='transferencia').update(tipo_metodo='cuenta_bancaria')
    
    print("✅ Actualizado ComisionMetodoPago: transferencia → cuenta_bancaria")


def reverse_update(apps, schema_editor):
    """
    Revierte los cambios (para rollback)
    """
    ComisionMetodoPago = apps.get_model('payments', 'ComisionMetodoPago')
    
    # Revertir cambios
    ComisionMetodoPago.objects.filter(tipo_metodo='cuenta_bancaria').update(tipo_metodo='transferencia')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_comisionmetodopago_tipo_metodo'),
    ]

    operations = [
        migrations.RunPython(update_transferencia_to_cuenta_bancaria, reverse_update),
    ]
