# Generated by Django 5.2.5 on 2025-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_transferencia_and_update_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionmetodopago',
            name='tipo_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia'), ('cuenta_bancaria', 'Cuenta Bancaria'), ('billetera', 'Billetera')], max_length=20, unique=True),
        ),
    ]
