# Generated by Django 5.2.5 on 2025-11-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0004_transaccion_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPasarela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pago_externo', models.CharField(help_text='ID único del pago en la pasarela (o UUID generado)', max_length=100, unique=True, verbose_name='ID Pago Externo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('metodo_pasarela', models.CharField(help_text='Método: tarjeta, billetera, transferencia, cuenta_interna', max_length=50, verbose_name='Método en Pasarela')),
                ('moneda', models.CharField(max_length=10, verbose_name='Moneda')),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('fallo', 'Fallo'), ('pendiente', 'Pendiente')], max_length=20, verbose_name='Estado del Pago')),
                ('datos_pago', models.JSONField(blank=True, default=dict, help_text='Datos enviados a la pasarela', verbose_name='Datos del Pago')),
                ('respuesta_pasarela', models.JSONField(blank=True, default=dict, help_text='Respuesta completa de la pasarela', verbose_name='Respuesta de Pasarela')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pasarela', to='transaccion.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago de Pasarela',
                'verbose_name_plural': 'Pagos de Pasarela',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['id_pago_externo'], name='pagos_pagop_id_pago_4fa437_idx'), models.Index(fields=['transaccion', '-fecha_creacion'], name='pagos_pagop_transac_0b10ce_idx'), models.Index(fields=['estado', '-fecha_creacion'], name='pagos_pagop_estado_9cf2ca_idx')],
            },
        ),
    ]
