# Generated by Django 5.2.5 on 2025-11-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopasarela',
            name='mensaje_error',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mensaje de Error'),
        ),
    ]
