from sqlalchemy.orm import relationship, Mapped, mapped_column
from sqlalchemy.ext.mutable import MutableList, List
from sqlalchemy import Boolean, DateTime, Column, Integer, \
                       String, ForeignKey, BigInteger, Text
from sqlalchemy.sql import func
from fs_proxy.db import db
import logging

def row2dict(row):    
    d = {}
    for column in row.__table__.columns:
        logging.debug(f"column: {column.name}")
        d[column.name] = str(getattr(row, column.name))
    return d

class Esi(db.Model):
    __tablename__ = 'esi'
    __table_args__ = {'quote': False}
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    ruc = Column('ruc', String(20), unique=True, quote=False)
    ruc_dv = Column('ruc_dv', String(1), nullable=False, quote=False)
    nombre = Column('nombre', String(200), nullable=False, quote=False)
    descripcion = Column('descripcion', Text, quote=False)
    estado = Column('estado', String(50), nullable=False, quote=False)
    fch_ins = Column('fch_ins', DateTime(), server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), server_default=func.now(), onupdate=func.now(), quote=False)
    esi_email = Column('esi_email', String(200), nullable=False, quote=False)
    esi_passwd = Column('esi_passwd', String(200), nullable=False, quote=False)
    esi_token = Column('esi_token', Text, quote=False)
    esi_url = Column('esi_url', String(200), nullable=False, quote=False)

class DE(db.Model):
    __tablename__ = 'de'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    iTiDE = Column('iTiDE', String(10), quote=False)
    dFeEmiDE = Column('dFeEmiDE', String(20), quote=False)
    dEst = Column('dEst', String(10), quote=False)
    dPunExp = Column('dPunExp', String(10), quote=False)
    dNumDoc = Column('dNumDoc', String(20), quote=False)
    CDC = Column('CDC', String(100), quote=False)
    dSerieNum = Column('dSerieNum', String(10), quote=False)
    estado = Column('estado', String(50), quote=False)
    estado_sifen = Column('estado_sifen', String(50), quote=False)
    desc_sifen = Column('desc_sifen', Text, quote=False)
    error_sifen = Column('error_sifen', Text, quote=False)
    fch_sifen = Column('fch_sifen', String(20), quote=False)
    estado_can = Column('estado_can', String(50), quote=False)
    desc_can = Column('desc_can', Text, quote=False)
    error_can = Column('error_can', Text, quote=False)
    fch_can = Column('fch_can', String(20), quote=False)
    estado_inu = Column('estado_inu', String(50), quote=False)
    desc_inu = Column('desc_inu', Text, quote=False)
    error_inu = Column('error_inu', Text, quote=False)
    fch_inu = Column('fch_inu', String(20), quote=False)
    iTipEmi = Column('iTipEmi', String(10), quote=False)
    dNumTim = Column('dNumTim', String(20), quote=False)
    dFeIniT = Column('dFeIniT', String(20), quote=False)
    iTipTra = Column('iTipTra', String(10), quote=False)
    iTImp = Column('iTImp', String(10), quote=False)
    cMoneOpe = Column('cMoneOpe', String(10), quote=False)
    dTiCam = Column('dTiCam', String(20), quote=False)
    dInfoFisc = Column('dInfoFisc', Text, quote=False)
    dRucEm = Column('dRucEm', String(20), quote=False)
    dDVEmi = Column('dDVEmi', String(10), quote=False)
    iTipCont = Column('iTipCont', String(10), quote=False)
    dNomEmi = Column('dNomEmi', Text, quote=False)
    dDirEmi = Column('dDirEmi', Text, quote=False)
    dNumCas = Column('dNumCas', String(10), quote=False)
    cDepEmi = Column('cDepEmi', String(10), quote=False)
    dDesDepEmi = Column('dDesDepEmi', String(50), quote=False)
    cCiuEmi = Column('cCiuEmi', String(10), quote=False)
    dDesCiuEmi = Column('dDesCiuEmi', String(50), quote=False)
    dTelEmi = Column('dTelEmi', String(50), quote=False)
    dEmailE = Column('dEmailE', String(200), quote=False)
    iNatRec = Column('iNatRec', String(10), quote=False)
    iTiOpe = Column('iTiOpe', String(10), quote=False)
    cPaisRec = Column('cPaisRec', String(10), quote=False)
    iTiContRec = Column('iTiContRec', String(10), quote=False)
    dRucRec = Column('dRucRec', String(20), quote=False)
    dDVRec = Column('dDVRec', String(10), quote=False)
    iTipIDRec = Column('iTipIDRec', String(10), quote=False)
    dDTipIDRec = Column('dDTipIDRec', String(100), quote=False)
    dNumIDRec = Column('dNumIDRec', String(50), quote=False)
    dNomRec = Column('dNomRec', Text, quote=False)
    dEmailRec = Column('dEmailRec', String(200), quote=False)
    dDirRec = Column('dDirRec', String(20), quote=False)
    dNumCasRec = Column('dNumCasRec', String(10), quote=False)
    cDepRec = Column('cDepRec', String(10), quote=False)
    dDesDepRec = Column('dDesDepRec', String(50), quote=False)
    cCiuRec = Column('cCiuRec', String(10), quote=False)
    dDesCiuRec = Column('dDesCiuRec', String(50), quote=False)
    iNatVen = Column('iNatVen', String(10), quote=False)
    iTipIDVen = Column('iTipIDVen', String(10), quote=False)
    dNumIDVen = Column('dNumIDVen', String(50), quote=False)
    dNomVen = Column('dNomVen', String(100), quote=False)
    dDirVen = Column('dDirVen', Text, quote=False)
    dNumCasVen = Column('dNumCasVen', String(10), quote=False)
    cDepVen = Column('cDepVen', String(10), quote=False)
    dDesDepVen = Column('dDesDepVen', String(50), quote=False)
    cCiuVen = Column('cCiuVen', String(10), quote=False)
    dDesCiuVen = Column('dDesCiuVen', String(50), quote=False)
    dDirProv = Column('dDirProv', Text, quote=False)
    cDepProv = Column('cDepProv', String(10), quote=False)
    dDesDepProv = Column('dDesDepProv', String(50), quote=False)
    cCiuProv = Column('cCiuProv', String(10), quote=False)
    dDesCiuProv = Column('dDesCiuProv', String(50), quote=False)
    iMotEmi = Column('iMotEmi', String(10), quote=False)
    iIndPres = Column('iIndPres', String(10), quote=False)
    iCondOpe = Column('iCondOpe', String(10), quote=False)
    dPlazoCre = Column('dPlazoCre', String(50), quote=False)
    dModCont = Column('dModCont', String(10), quote=False)
    dEntCont = Column('dEntCont', String(10), quote=False)
    dAnoCont = Column('dAnoCont', String(10), quote=False)
    dSecCont = Column('dSecCont', String(20), quote=False)
    dFeCodCont = Column('dFeCodCont', String(20), quote=False)
    dSisFact = Column('dSisFact', String(10), quote=False)
    dInfAdic = Column('dInfAdic', Text, quote=False)
    iMotEmiNR = Column('iMotEmiNR', String(10), quote=False)
    iRespEmiNR = Column('iRespEmiNR', String(10), quote=False)
    iTipTrans = Column('iTipTrans', String(10), quote=False)
    iModTrans = Column('iModTrans', String(10), quote=False)
    iRespFlete = Column('iRespFlete', String(10), quote=False)
    dIniTras = Column('dIniTras', String(20), quote=False)
    dFinTras = Column('dFinTras', String(20), quote=False)
    dDirLocSal = Column('dDirLocSal', Text, quote=False)
    dNumCasSal = Column('dNumCasSal', String(10), quote=False)
    cDepSal = Column('cDepSal', String(10), quote=False)
    dDesDepSal = Column('dDesDepSal', String(50), quote=False)
    cCiuSal = Column('cCiuSal', String(10), quote=False)
    dDesCiuSal = Column('dDesCiuSal', String(50), quote=False)
    dDirLocEnt = Column('dDirLocEnt', Text, quote=False)
    dNumCasEnt = Column('dNumCasEnt', String(10), quote=False)
    cDepEnt = Column('cDepEnt', String(10), quote=False)
    dDesDepEnt = Column('dDesDepEnt', String(50), quote=False)
    cCiuEnt = Column('cCiuEnt', String(10), quote=False)
    dDesCiuEnt = Column('dDesCiuEnt', String(50), quote=False)
    dTiVehTras = Column('dTiVehTras', String(20), quote=False)
    dMarVeh = Column('dMarVeh', String(20), quote=False)
    dTipIdenVeh = Column('dTipIdenVeh', String(10), quote=False)
    dNroIDVeh = Column('dNroIDVeh', String(50), quote=False)
    dNroMatVeh = Column('dNroMatVeh', String(50), quote=False)
    iNatTrans = Column('iNatTrans', String(10), quote=False)
    dNomTrans = Column('dNomTrans', String(100), quote=False)
    dRucTrans = Column('dRucTrans', String(20), quote=False)
    dDVTrans = Column('dDVTrans', String(10), quote=False)
    iTipIDTrans = Column('iTipIDTrans', String(10), quote=False)
    dNumIDTrans = Column('dNumIDTrans', String(50), quote=False)
    dNumIDChof = Column('dNumIDChof', String(50), quote=False)
    dNomChof = Column('dNomChof', String(100), quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    DE_files: Mapped[List["DE_file"]] = relationship(back_populates="de")
    gActEcos: Mapped[List["gActEco"]] = relationship(back_populates="de")
    gPaConEInis: Mapped[List["gPaConEIni"]] = relationship(back_populates="de")
    gCamDEAsocs: Mapped[List["gCamDEAsoc"]] = relationship(back_populates="de")
    gCamItems: Mapped[List["gCamItem"]] = relationship(back_populates="de")

            
class DE_file(db.Model):
    __tablename__ = 'de_file'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    tipo = Column('tipo', String(10), quote=False)
    path = Column('path', String(200), quote=False)
    estado = Column('estado', String(50), quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    de_id: Mapped[BigInteger] = mapped_column('de_id', ForeignKey("de.id"), quote=False)
    de: Mapped["DE"] = relationship(back_populates="DE_files")

class gActEco(db.Model):
    __tablename__ = 'gActEco'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    cActEco = Column('cActEco', String(20), quote=False)
    dDesActEco = Column('dDesActEco', Text, quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    de_id: Mapped[BigInteger] = mapped_column('de_id', ForeignKey("de.id"), quote=False)
    de: Mapped["DE"] = relationship(back_populates="gActEcos")

class gPaConEIni(db.Model):
    __tablename__ = 'gPaConEIni'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    iTiPago = Column('iTiPago', String(10), quote=False)
    dMonTiPag = Column('dMonTiPag', String(50), quote=False)
    cMoneTiPag = Column('cMoneTiPag', String(10), quote=False)
    dTiCamTiPag = Column('dTiCamTiPag', String(20), quote=False)
    dNumCheq = Column('dNumCheq', String(20), quote=False)
    dBcoEmi = Column('dBcoEmi', String(50), quote=False)
    iDenTarj = Column('iDenTarj', String(10), quote=False)
    iForProPa = Column('iForProPa', String(10), quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    de_id: Mapped[BigInteger] = mapped_column('de_id', ForeignKey("de.id"), quote=False)
    de: Mapped["DE"] = relationship(back_populates="gPaConEInis")

class gCamDEAsoc(db.Model):
    __tablename__ = 'gCamDEAsoc'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    iTipDocAso = Column('iTipDocAso', String(10), quote=False)
    dCdCDERef = Column('dCdCDERef', String(100), quote=False)
    dNTimDI = Column('dNTimDI', String(20), quote=False)
    dEstDocAso = Column('dEstDocAso', String(10), quote=False)
    dPExpDocAso = Column('dPExpDocAso', String(10), quote=False)
    dNumDocAso = Column('dNumDocAso', String(20), quote=False)
    iTipoDocAso = Column('iTipoDocAso', String(10), quote=False)
    dFecEmiDI = Column('dFecEmiDI', String(20), quote=False)
    dNumComRet = Column('dNumComRet', String(50), quote=False)
    dNumResCF = Column('dNumResCF', String(50), quote=False)
    iTipCons = Column('iTipCons', String(10), quote=False)
    dNumCons = Column('dNumCons', String(50), quote=False)
    dNumControl = Column('dNumControl', String(20), quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    de_id: Mapped[BigInteger] = mapped_column('de_id', ForeignKey("de.id"), quote=False)
    de: Mapped["DE"] = relationship(back_populates="gCamDEAsocs")

class gCamItem(db.Model):
    __tablename__ = 'gCamItem'
    __table_args__ = {'quote': False}
    id = Column('id', BigInteger, primary_key=True, quote=False)
    dCodInt = Column('dCodInt', String(100), quote=False)
    dDesProSer = Column('dDesProSer', String(200), quote=False)
    dCantProSer = Column('dCantProSer', String(30), quote=False)
    dPUniProSer = Column('dPUniProSer', String(50), quote=False)
    dDescItem = Column('dDescItem', String(50), quote=False)
    iAfecIVA = Column('iAfecIVA', String(10), quote=False)
    dPropIVA = Column('dPropIVA', String(10), quote=False)
    dTasaIVA = Column('dTasaIVA', String(10), quote=False)
    dParAranc = Column('dParAranc', String(10), quote=False)
    dNCM = Column('dNCM', String(20), quote=False)
    dDncpG = Column('dDncpG', String(20), quote=False)
    dDncpE = Column('dDncpE', String(10), quote=False)
    dGtin = Column('dGtin', String(50), quote=False)
    dGtinPq = Column('dGtinPq', String(50), quote=False)
    fch_ins = Column('fch_ins', DateTime(), nullable=False, server_default=func.now(), quote=False)
    fch_upd = Column('fch_upd', DateTime(), nullable=False, server_default=func.now(), onupdate=func.now(), quote=False)
    de_id: Mapped[BigInteger] = mapped_column('de_id', ForeignKey("de.id"), quote=False)
    de: Mapped["DE"] = relationship(back_populates="gCamItems")