# Generated by Django 5.2.5 on 2025-11-18 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
            ],
        ),
    ]
