# Generated by Django 5.2.5 on 2025-11-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0008_alter_tasacambio_variacion'),
        ('tauser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('type', models.CharField(choices=[('bill', 'Billete'), ('coin', 'Moneda')], max_length=10, verbose_name='Tipo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominaciones', to='monedas.moneda')),
            ],
            options={
                'verbose_name': 'Denominación',
                'verbose_name_plural': 'Denominaciones',
                'unique_together': {('moneda', 'value', 'type')},
            },
        ),
        migrations.CreateModel(
            name='TauserStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tauser.denominacion')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='tauser.tauser')),
            ],
            options={
                'verbose_name': 'Stock de TAUser',
                'verbose_name_plural': 'Stock de TAUsers',
                'unique_together': {('tauser', 'denominacion')},
            },
        ),
    ]
