# Generated by Django 5.2.5 on 2025-11-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0004_auto_poblar_tauser_stock'),
        ('transaccion', '0009_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStockTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('salida', 'Salida'), ('entrada', 'Entrada')], max_length=10)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tauser.denominacion')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tauser.tauser')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='transaccion.transaccion')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock de Tauser',
                'verbose_name_plural': 'Movimientos de Stock de Tauser',
            },
        ),
    ]
