# Generated by Django 5.2.5 on 2025-11-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0005_movimientostocktauser'),
        ('transaccion', '0009_alter_transaccion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaDenominacionTauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad reservada')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tauser.denominacion')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_denominaciones', to='tauser.tauser')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_denominaciones', to='transaccion.transaccion')),
            ],
            options={
                'verbose_name': 'Reserva de Denominación de TAUser',
                'verbose_name_plural': 'Reservas de Denominaciones de TAUser',
                'unique_together': {('tauser', 'transaccion', 'denominacion')},
            },
        ),
        migrations.DeleteModel(
            name='MovimientoStockTauser',
        ),
    ]
