# Generated by Django 5.2.8 on 2025-11-27 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tauser', '0006_reservadenominaciontauser_and_more'),
        ('transaccion', '0010_transaccion_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauserStockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad movida')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tauser.denominacion')),
                ('tauser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tauser.tauser')),
                ('transaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='transaccion.transaccion')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock de TAUser',
                'verbose_name_plural': 'Movimientos de Stock de TAUser',
                'ordering': ['-fecha'],
            },
        ),
    ]
