# Generated by Django 5.2.5 on 2025-11-23 20:07

import transaccion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_limiteclientetipo'),
        ('monedas', '0008_alter_tasacambio_variacion'),
        ('payments', '0011_remove_paymentmethod_cheque_banco_and_more'),
        ('transaccion', '0004_transaccion_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='codigo_verificacion',
            field=models.CharField(default=transaccion.models.generar_codigo_verificacion, editable=False, max_length=10, unique=True, verbose_name='Código de Verificación'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='datos_metodo_pago',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos del Método de Pago'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Expiración'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['codigo_verificacion'], name='transaccion_codigo__ec8bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado', 'fecha'], name='transaccion_estado_2a2541_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cliente', 'fecha'], name='transaccion_cliente_dbb499_idx'),
        ),
    ]
