# Generated by Django 5.2.5 on 2025-11-24 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_acreditacion', '0005_alter_medioacreditacion_tipo_medio'),
        ('tauser', '0004_auto_poblar_tauser_stock'),
        ('transaccion', '0005_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='datos_metodo_pago',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medio_cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='medios_acreditacion.medioacreditacion', verbose_name='Medio de Cobro'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='tauser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='tauser.tauser', verbose_name='Tauser'),
        ),
    ]
