# Generated by Django 5.2.5 on 2025-11-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0006_remove_transaccion_datos_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo_metodo_pago',
            field=models.CharField(blank=True, help_text='Indica el método usado: efectivo, tarjeta, transferencia, billetera', max_length=20, null=True, verbose_name='Tipo de Método de Pago/Cobro'),
        ),
    ]
