# Generated by Django 5.2.5 on 2025-11-24 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0007_agregar_tipo_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='tipo_metodo_pago',
        ),
    ]
