# Generated by Django 5.2.5 on 2025-11-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0008_remove_transaccion_tipo_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=15),
        ),
    ]
