# Generated by Django 5.2.5 on 2025-11-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0009_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia obtenida en la transacción (comisión + spread + otros).', max_digits=18, null=True, verbose_name='Ganancia'),
        ),
    ]
