# Generated by Django 5.2.5 on 2025-11-25 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0005_alter_transaccion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc_emisor', models.CharField(max_length=20, verbose_name='RUC Emisor')),
                ('dv_emisor', models.CharField(max_length=2, verbose_name='DV Emisor')),
                ('nombre_emisor', models.CharField(max_length=300, verbose_name='Razón Social Emisor')),
                ('direccion_emisor', models.CharField(max_length=300, verbose_name='Dirección Emisor')),
                ('numero_casa', models.CharField(max_length=10, verbose_name='Número de Casa')),
                ('departamento_emisor', models.CharField(default='1', max_length=3, verbose_name='Código Departamento')),
                ('descripcion_departamento', models.CharField(default='CAPITAL', max_length=100, verbose_name='Descripción Departamento')),
                ('ciudad_emisor', models.CharField(default='1', max_length=3, verbose_name='Código Ciudad')),
                ('descripcion_ciudad', models.CharField(default='ASUNCION (DISTRITO)', max_length=100, verbose_name='Descripción Ciudad')),
                ('telefono_emisor', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Emisor')),
                ('email_emisor', models.EmailField(max_length=254, verbose_name='Email Emisor')),
                ('numero_timbrado', models.CharField(max_length=20, verbose_name='Número de Timbrado')),
                ('fecha_inicio_timbrado', models.DateField(verbose_name='Fecha Inicio Timbrado')),
                ('sql_proxy_url', models.URLField(default='http://sql-proxy01:5000', verbose_name='URL SQL Proxy')),
                ('activo', models.BooleanField(default=True, verbose_name='Configuración Activa')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cdc', models.CharField(max_length=200, unique=True, verbose_name='Código de Control')),
                ('id_de', models.BigIntegerField(blank=True, null=True, verbose_name='ID Documento Electrónico')),
                ('numero_factura', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('estado_sifen', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('APROBADO', 'Aprobado'), ('APROBADO_OBS', 'Aprobado con Observación'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado SIFEN')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación SIFEN')),
                ('fecha_consulta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Consulta')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='facturas/xml/', verbose_name='Archivo XML')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='facturas/pdf/', verbose_name='Archivo PDF')),
                ('descripcion_estado', models.TextField(blank=True, verbose_name='Descripción del Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('intentos_consulta', models.IntegerField(default=0, verbose_name='Intentos de Consulta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura_electronica', to='transaccion.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Factura Electrónica',
                'verbose_name_plural': 'Facturas Electrónicas',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['cdc'], name='facturacion_cdc_d25736_idx'), models.Index(fields=['estado_sifen'], name='facturacion_estado__d3c1c8_idx'), models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_a9cd4a_idx')],
            },
        ),
    ]
