# Generated by Django 5.2.5 on 2025-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='cedula_receptor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Receptor'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='direccion_receptor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección del Receptor'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='dv_receptor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='DV del RUC'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='email_receptor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Receptor'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='nombre_receptor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre del Receptor'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='ruc_receptor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC del Receptor'),
        ),
    ]
