# Generated by Django 5.2.5 on 2025-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_facturaelectronica_cedula_receptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Factura'),
        ),
    ]
