# Generated by Django 5.2.5 on 2025-11-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_facturaelectronica_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='cdc',
            field=models.CharField(max_length=200, verbose_name='Código de Control'),
        ),
    ]
