# Generated by Django 5.2.5 on 2025-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_facturaelectronica_cdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='desc_sifen',
            field=models.CharField(blank=True, help_text='Descripción detallada del estado desde SIFEN', max_length=200, verbose_name='Descripción Estado SIFEN'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='error_sifen',
            field=models.TextField(blank=True, help_text='Mensaje de error devuelto por SIFEN', verbose_name='Error SIFEN'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='cdc',
            field=models.CharField(blank=True, max_length=200, verbose_name='Código de Control'),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='estado_sifen',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('APROBADO', 'Aprobado'), ('APROBADO_OBS', 'Aprobado con Observación'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error'), ('CANCELADO', 'Cancelado'), ('INUTILIZADO', 'Inutilizado'), ('REEMPLAZADA', 'Reemplazada')], default='PENDIENTE', max_length=20, verbose_name='Estado SIFEN'),
        ),
    ]
